name: codeclimate

on:
  push:
    branches:
      - '**'

steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v2.7.5
    env:
      CC_TEST_REPORTER_ID: ffb07d90d7ba252a41cd54f436d62da5c521994fd7b0f24ca168db250c90eeab
    with:
      coverageCommand: yarn coverage
      debug: true
